version: '2'
services:
  frontend:
    build: .
    # command: bash -c 'cd /opt/app && npm install && npm start'
    command: bash -c 'cd /opt/app && ng new givemecoffee-frontend'
    ports:
      - '4200:4200'
    volumes:
      - './frontend:/opt/app'
